# use c and gcc
language: c
compiler: gcc

# before build script, run autoreconf
before_script: autoreconf --install

# Default is "./configure && make && make test", but no tests yet
script: "./configure --enable-notmuch --enable-sidebar && make"

